### ISSUE TITLE
Support "check" by bladebit at end of each plotting

### ISSUE THREAD

**Issue by guydavis** [guydavis/plotman#51]
Add support for `check: true/false` with `false` as defualt to bladebit plotter config.  

Questions: 

1. Should check time be excluded from time measurement and charting?  Probably not as it is time taken during plotting.
2. Would want this plot check result to be used instead of a later async plot check result.

**Comment by ApfelBirneKreis** [comment]
1. since the check uses high gpu resources i believe it should be included. This check variable should only be used to sanity check if the new experimental 16G mode plots are usable or not. I added a pull request for enabling the variable in  16G and 128G mode. Pls check it out before merging.

2. I would suggest so. Later we should add a popup in the Plotman Config to tell the user that this variable should only used vor validation and Testing.

Additionally later we can add a plot deletion if the check failed. But im currently fine with manual validation.

**Comment by ApfelBirneKreis** [comment]
All features implemented. Can be marked as done. Out for broad testing in `machinaris:develop`.
